version: '3'
services:
    db:
      image: postgres:12
      container_name: db-container
      ports: 
          - 5432:5432
      volumes:
          - /var/lib/postgresql/data/pgdata
      env_file:
          - .local.env
  
    redis:
      image: redis
      container_name: redis-container
      ports:
        - "6379:6379"

    backend:
      image: backend:latest-local
      container_name: backend-container
      env_file:
          - .local.env
      build:
          context: .
          dockerfile: backend.Dockerfile
      depends_on:
          - db
      volumes:
          - ./app:/app
          - ./alembic:/alembic
      ports:
          - 8000:8000