version: '3'
services:
    db:
        image: postgres:12
        ports: 
            - 5432:5432
        volumes:
            - /var/lib/postgresql/data/pgdata
        env_file:
            - .local.env
        
    backend:
        image: backend:latest-local
        env_file:
            - .local.env
        build:
            context: .
            dockerfile: backend.Dockerfile
        depends_on:
            - db
        volumes:
            - ./app:/app
            - ./alembic:/alembic
        ports:
            - 8000:8000